services:
  backend:
  build: ./backend
  expose:
    - "3000"
  env_file:
    - ./backend/.env
  frontend:
    build: ./frontend
    expose:
      - "3000"
    depends_on:
      - backend

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - frontend
      - backend