services:
  backend:
    build: ./backend
    expose:
      - "8000"
    environment:
      - MONGO_URI=mongodb+srv://dudecandy883:dudecandy883@cluster0.b97fe0t.mongodb.net

  frontend:
    build: ./frontend
    expose:
      - "3000"
    depends_on:
      - backend

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - frontend
      - backend