server {
    listen 80 default_server;
    server_name _;
    return 444;
}

server {
    listen 80;
    server_name devtech2026.duckdns.org;

    client_max_body_size 50M;

    set $frontend frontend_green;

    if (-f /etc/nginx/active_blue) {
        set $frontend frontend_blue;
    }

    location / {
        proxy_pass http://$frontend:3000;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }

    location /api/ {
        proxy_pass http://backend:5000;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }
}