upstream frontend_upstream {
    server frontend_green:3000;
    server frontend_blue:3000;
}

server {
    listen 80;
    server_name devtech2026.duckdns.org;

    client_max_body_size 50M;

    location / {
        proxy_pass http://frontend_upstream;
        proxy_http_version 1.1;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header Connection "";
    }

    location /api/ {
        proxy_pass http://backend:5000;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }
}