name: Build & Deploy Docker Images

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Login to GHCR
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Set Image Name
        run: echo "IMAGE=ghcr.io/${{ github.repository }}" >> $GITHUB_ENV

      - name: Build Backend Image
        run: docker build -t $IMAGE/backend ./backend

      - name: Build Frontend Image
        run: docker build -t $IMAGE/frontend ./frontend

      - name: Push Backend Image
        run: docker push $IMAGE/backend

      - name: Push Frontend Image
        run: docker push $IMAGE/frontend

      - name: Blue/Green Deploy (Zero Downtime)
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ec2-user
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            cd /home/ec2-user/bro

            ACTIVE=$(cat nginx/active_env 2>/dev/null || echo green)

            echo "Current ACTIVE: $ACTIVE"

            if [ "$ACTIVE" = "green" ]; then

              echo "Deploying BLUE..."

              docker compose up -d --no-deps frontend_blue
              docker compose up -d --no-deps backend

              sleep 10

              rm -f nginx/active_green
              touch nginx/active_blue
              echo "blue" > nginx/active_env

            else

              echo "Deploying GREEN..."

              docker compose up -d --no-deps frontend_green
              docker compose up -d --no-deps backend

              sleep 10

              rm -f nginx/active_blue
              touch nginx/active_env
              echo "green" > nginx/active_env

            fi

            docker exec bro-nginx-1 nginx -s reload